
export const HERO_AFTERGLOW_BOOTH_CONFIG = {
  "width": 10,
  "depth": 7,
  "wallThickness": 0.1,
  "walls": {
    "north": true,
    "south": false,
    "east": false,
    "west": false
  },
  "floorType": "tile",
  "floorColor": "#514A68"
};

export const HERO_AFTERGLOW_ELEMENTS = [
  {
    "id": "outer-north",
    "type": "wall",
    "isOuter": true,
    "x": 500,
    "y": 0,
    "width": 1000,
    "thickness": 10,
    "rotation": 0,
    "wallElements": [
      {
        "id": "up6wi071y",
        "type": "light",
        "x": 130,
        "y": 40,
        "width": 90,
        "height": 90,
        "shape": "square",
        "lightColor": "#9966ff",
        "intensity": 0.3,
        "model": "wall_light_2"
      },
      {
        "id": "32pjl1e7n",
        "type": "light",
        "x": 460,
        "y": 40,
        "width": 90,
        "height": 90,
        "shape": "square",
        "lightColor": "#ff00ff",
        "intensity": 0.6,
        "model": "wall_light_2"
      },
      {
        "id": "uvcmavr6m",
        "type": "light",
        "x": 780,
        "y": 40,
        "width": 90,
        "height": 90,
        "shape": "square",
        "lightColor": "#00eeff",
        "intensity": 0.6,
        "model": "wall_light_2"
      },
      {
        "id": "81abnmoxs",
        "type": "light",
        "x": 30,
        "y": 230,
        "width": 940,
        "height": 10,
        "shape": "square",
        "lightColor": "#00eeff",
        "intensity": 0.5,
        "model": "wall_light_3"
      },
      {
        "id": "3ekrrrej4",
        "type": "light",
        "x": 320,
        "y": 40,
        "width": 10,
        "height": 170,
        "shape": "square",
        "lightColor": "#00eeff",
        "intensity": 0.5,
        "model": "wall_light_1"
      },
      {
        "id": "j84we0a2d",
        "type": "light",
        "x": 650,
        "y": 40,
        "width": 10,
        "height": 170,
        "shape": "square",
        "lightColor": "#ff00ff",
        "intensity": 0.5,
        "model": "wall_light_1"
      }
    ],
    "material": "custom_color",
    "fill": "#f0f0f0",
    "opacity": 1,
    "color": "#30254F"
  },
  {
    "id": "ab90fa21-bbc4-4526-a027-b13672943fbd",
    "type": "asset",
    "assetName": "soft_ii_ho111051",
    "categoryFolder": "armchairs-sofas-and-lounges",
    "label": "Soft II",
    "details": "Length/dept: 132 cm; Width: 79 cm; Height: 82 cm; Sit height: 42 cm; Stackable: No; Swivel: No; Linkable: No; Frame: Wood; Sustainable: No; Seating: Upholstered",
    "x": 100,
    "y": 229.99999999999997,
    "rotation": 90,
    "width": 132,
    "height": 79,
    "specH": 0.82,
    "realWidth": 1.32,
    "realHeight": 0.82,
    "realDepth": 0.79,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": -90
  },
  {
    "id": "85bff644-f3c8-4ac6-8426-cc486dfeb4b6",
    "type": "asset",
    "assetName": "soft_ii_ho111051",
    "categoryFolder": "armchairs-sofas-and-lounges",
    "label": "Soft II",
    "details": "Length/dept: 132 cm; Width: 79 cm; Height: 82 cm; Sit height: 42 cm; Stackable: No; Swivel: No; Linkable: No; Frame: Wood; Sustainable: No; Seating: Upholstered",
    "x": 100,
    "y": 375,
    "rotation": 90,
    "width": 132,
    "height": 79,
    "specH": 0.82,
    "realWidth": 1.32,
    "realHeight": 0.82,
    "realDepth": 0.79,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": -90
  },
  {
    "id": "9f4916e6-507f-4e5b-90cd-e59eea7265f9",
    "type": "asset",
    "assetName": "egg_chair_ho104919",
    "categoryFolder": "armchairs-sofas-and-lounges",
    "label": "Egg Chair",
    "details": "Length/dept: 95 cm; Width: 86 cm; Height: 107 cm; Sit height: 37 cm; Stackable: No; Swivel: Yes; Linkable: No; Frame: aluminium polished; Sustainable: No; Designer: Arne Jacobsen; Seating: Upholstery",
    "x": 340,
    "y": 220.00000000000003,
    "rotation": 270,
    "width": 86,
    "height": 95,
    "specH": 1.07,
    "realWidth": 0.86,
    "realHeight": 1.07,
    "realDepth": 0.95,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "1e14fd55-7398-4cc4-bbc0-61b5c4d245b9",
    "type": "asset",
    "assetName": "egg_chair_ho104919",
    "categoryFolder": "armchairs-sofas-and-lounges",
    "label": "Egg Chair",
    "details": "Length/dept: 95 cm; Width: 86 cm; Height: 107 cm; Sit height: 37 cm; Stackable: No; Swivel: Yes; Linkable: No; Frame: aluminium polished; Sustainable: No; Designer: Arne Jacobsen; Seating: Upholstery",
    "x": 340,
    "y": 380,
    "rotation": 270,
    "width": 86,
    "height": 95,
    "specH": 1.07,
    "realWidth": 0.86,
    "realHeight": 1.07,
    "realDepth": 0.95,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "357a08fa-caf8-4d0e-9b89-b9219618582d",
    "type": "asset",
    "assetName": "little_friend_ho110626",
    "categoryFolder": "tables-and-bar-tables",
    "label": "Little Friend",
    "details": "Length/dept: 45 cm; Width: 45 cm; Height: 50-73 cm; Frame: steelpipe; Table top: Laminate; Table top color: Laminate; Sustainable: No; Has plug: No",
    "x": 220.00000000000003,
    "y": 235,
    "rotation": 0,
    "width": 45,
    "height": 45,
    "specH": null,
    "realWidth": 0.45,
    "realHeight": 1,
    "realDepth": 0.45,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "2a28e67f-9a77-4acb-ad66-0dd31332a16a",
    "type": "asset",
    "assetName": "little_friend_ho110626",
    "categoryFolder": "tables-and-bar-tables",
    "label": "Little Friend",
    "details": "Length/dept: 45 cm; Width: 45 cm; Height: 50-73 cm; Frame: steelpipe; Table top: Laminate; Table top color: Laminate; Sustainable: No; Has plug: No",
    "x": 220.00000000000003,
    "y": 370,
    "rotation": 0,
    "width": 45,
    "height": 45,
    "specH": null,
    "realWidth": 0.45,
    "realHeight": 1,
    "realDepth": 0.45,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "712ad2d9-3442-4cd7-8bd7-004f06411ad5",
    "type": "asset",
    "assetName": "lumino_buffet",
    "categoryFolder": "counters-and-showcases",
    "label": "Lumino Buffet",
    "details": "Length/dept: 66 cm; Width: 100 cm; Height: 86 cm; Lockable: No; Illuminated: Yes; Frame: Wood; LED: No; Sustainable: No; Has plug: Yes",
    "x": 680,
    "y": 170,
    "rotation": 90,
    "width": 100,
    "height": 66,
    "specH": 0.86,
    "realWidth": 1,
    "realHeight": 0.86,
    "realDepth": 0.66,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "b76881db-c264-40a8-82e8-bb99b20a5be7",
    "type": "asset",
    "assetName": "lumino_buffet",
    "categoryFolder": "counters-and-showcases",
    "label": "Lumino Buffet",
    "details": "Length/dept: 66 cm; Width: 100 cm; Height: 86 cm; Lockable: No; Illuminated: Yes; Frame: Wood; LED: No; Sustainable: No; Has plug: Yes",
    "x": 750,
    "y": 170,
    "rotation": 90,
    "width": 100,
    "height": 66,
    "specH": 0.86,
    "realWidth": 1,
    "realHeight": 0.86,
    "realDepth": 0.66,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "969aa96a-4c95-44e6-a159-41a0be1df5e7",
    "type": "asset",
    "assetName": "lumino_buffet",
    "categoryFolder": "counters-and-showcases",
    "label": "Lumino Buffet",
    "details": "Length/dept: 66 cm; Width: 100 cm; Height: 86 cm; Lockable: No; Illuminated: Yes; Frame: Wood; LED: No; Sustainable: No; Has plug: Yes",
    "x": 819.9999999999999,
    "y": 170,
    "rotation": 90,
    "width": 100,
    "height": 66,
    "specH": 0.86,
    "realWidth": 1,
    "realHeight": 0.86,
    "realDepth": 0.66,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "6115f818-aae5-42a4-b6d8-4290fa78be65",
    "type": "asset",
    "assetName": "petilia",
    "categoryFolder": "barstools-and-stools",
    "label": "Bombo",
    "details": "Length/dept: 40 cm; Width: 44 cm; Height: 61-85 cm; Sit height: 50 cm; Stackable: No; Swivel: Yes; Frame: Chrome Plated; Sustainable: No; Designer: Stefano Giovannoni; Seating: ABS polycarbonate",
    "x": 680,
    "y": 280,
    "rotation": 0,
    "width": 44,
    "height": 40,
    "specH": 0.5,
    "realWidth": 0.44,
    "realHeight": 0.5,
    "realDepth": 0.4,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "92bdf49a-6132-451c-9a93-7147357a1642",
    "type": "asset",
    "assetName": "petilia",
    "categoryFolder": "barstools-and-stools",
    "label": "Bombo",
    "details": "Length/dept: 40 cm; Width: 44 cm; Height: 61-85 cm; Sit height: 50 cm; Stackable: No; Swivel: Yes; Frame: Chrome Plated; Sustainable: No; Designer: Stefano Giovannoni; Seating: ABS polycarbonate",
    "x": 750,
    "y": 280,
    "rotation": 0,
    "width": 44,
    "height": 40,
    "specH": 0.5,
    "realWidth": 0.44,
    "realHeight": 0.5,
    "realDepth": 0.4,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "e154f925-6131-4db1-aa91-3687bb1cd031",
    "type": "asset",
    "assetName": "petilia",
    "categoryFolder": "barstools-and-stools",
    "label": "Bombo",
    "details": "Length/dept: 40 cm; Width: 44 cm; Height: 61-85 cm; Sit height: 50 cm; Stackable: No; Swivel: Yes; Frame: Chrome Plated; Sustainable: No; Designer: Stefano Giovannoni; Seating: ABS polycarbonate",
    "x": 819.9999999999999,
    "y": 280,
    "rotation": 0,
    "width": 44,
    "height": 40,
    "specH": 0.5,
    "realWidth": 0.44,
    "realHeight": 0.5,
    "realDepth": 0.4,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "44a4c72c-cd65-4131-b9e9-befbe1b5326e",
    "type": "asset",
    "assetName": "frigaro_gross_glastuer",
    "categoryFolder": "kitchen-and-miscellaneous",
    "label": "FRIGARO GROß GLASTÜR",
    "details": "Length/dept: 60 cm; Width: 60 cm; Height: 144 cm; Stackable: No; Illuminated: No; Frame: laquered metal; Swivel: No; Lockable: No; Linkable: No; LED: No; Sustainable: No; Has plug: No",
    "x": 919.9999999999999,
    "y": 65,
    "rotation": 180,
    "width": 60,
    "height": 60,
    "specH": 1.44,
    "realWidth": 0.6,
    "realHeight": 1.44,
    "realDepth": 0.6,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "252286a3-f96b-4d49-b603-36044bd3f321",
    "type": "asset",
    "assetName": "fermo_110_alufarben",
    "categoryFolder": "tables-and-bar-tables",
    "label": "FERMO 110 ALUFARBEN Ø 70",
    "details": "Height: 110 cm; Diameter: 70 cm; Frame: laquered metal; Table top: Wood; Table top color: Wood; Sustainable: No; Has plug: No",
    "x": 650,
    "y": 525,
    "rotation": 0,
    "width": 70,
    "height": 70,
    "specH": 1.1,
    "realWidth": 0.7,
    "realHeight": 1.1,
    "realDepth": 0.7,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "b383dae6-fd5b-4174-af2c-2333261e31b2",
    "type": "asset",
    "assetName": "fermo_110_alufarben",
    "categoryFolder": "tables-and-bar-tables",
    "label": "FERMO 110 ALUFARBEN Ø 70",
    "details": "Height: 110 cm; Diameter: 70 cm; Frame: laquered metal; Table top: Wood; Table top color: Wood; Sustainable: No; Has plug: No",
    "x": 865,
    "y": 525,
    "rotation": 0,
    "width": 70,
    "height": 70,
    "specH": 1.1,
    "realWidth": 0.7,
    "realHeight": 1.1,
    "realDepth": 0.7,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "2326e187-9949-4806-8fb5-3eae674e9afc",
    "type": "panel",
    "x": 12,
    "y": 300,
    "width": 459.99999999999994,
    "height": 12,
    "rotation": 90,
    "realWidth": 4.6,
    "realHeight": 1.1,
    "realDepth": 0.12,
    "style": "flat",
    "fill": "#794B8D"
  },
  {
    "id": "c0f63c44-346a-4d09-866a-a64c7aedb385",
    "type": "caged-wall",
    "x": 985,
    "y": 225,
    "width": 380,
    "height": 12,
    "rotation": 90,
    "realWidth": 3.8,
    "realHeight": 1.2,
    "realDepth": 0.12,
    "platesCount": 18,
    "plateThickness": 0.06,
    "plateGap": 0.15,
    "orientation": "vertical",
    "fill": "#367785"
  },
  {
    "id": "75e24e8d-719b-42fe-9f17-b6ddf9fab396",
    "type": "asset",
    "assetName": "petilia",
    "categoryFolder": "barstools-and-stools",
    "label": "Bombo",
    "details": "Length/dept: 40 cm; Width: 44 cm; Height: 61-85 cm; Sit height: 50 cm; Stackable: No; Swivel: Yes; Frame: Chrome Plated; Sustainable: No; Designer: Stefano Giovannoni; Seating: ABS polycarbonate",
    "x": 590,
    "y": 570,
    "rotation": 35,
    "width": 44,
    "height": 40,
    "specH": 0.5,
    "realWidth": 0.44,
    "realHeight": 0.5,
    "realDepth": 0.4,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "f14a30ca-a8e0-4f3b-b3bd-4006adc1b335",
    "type": "asset",
    "assetName": "petilia",
    "categoryFolder": "barstools-and-stools",
    "label": "Bombo",
    "details": "Length/dept: 40 cm; Width: 44 cm; Height: 61-85 cm; Sit height: 50 cm; Stackable: No; Swivel: Yes; Frame: Chrome Plated; Sustainable: No; Designer: Stefano Giovannoni; Seating: ABS polycarbonate",
    "x": 710,
    "y": 570,
    "rotation": -35,
    "width": 44,
    "height": 40,
    "specH": 0.5,
    "realWidth": 0.44,
    "realHeight": 0.5,
    "realDepth": 0.4,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "42af44d7-8f02-47d7-92a9-2671743eede0",
    "type": "asset",
    "assetName": "petilia",
    "categoryFolder": "barstools-and-stools",
    "label": "Bombo",
    "details": "Length/dept: 40 cm; Width: 44 cm; Height: 61-85 cm; Sit height: 50 cm; Stackable: No; Swivel: Yes; Frame: Chrome Plated; Sustainable: No; Designer: Stefano Giovannoni; Seating: ABS polycarbonate",
    "x": 810,
    "y": 570,
    "rotation": 35,
    "width": 44,
    "height": 40,
    "specH": 0.5,
    "realWidth": 0.44,
    "realHeight": 0.5,
    "realDepth": 0.4,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "2fca8d36-33ec-4db0-ae21-7a08607d5c0c",
    "type": "asset",
    "assetName": "petilia",
    "categoryFolder": "barstools-and-stools",
    "label": "Bombo",
    "details": "Length/dept: 40 cm; Width: 44 cm; Height: 61-85 cm; Sit height: 50 cm; Stackable: No; Swivel: Yes; Frame: Chrome Plated; Sustainable: No; Designer: Stefano Giovannoni; Seating: ABS polycarbonate",
    "x": 919.9999999999999,
    "y": 570,
    "rotation": -35,
    "width": 44,
    "height": 40,
    "specH": 0.5,
    "realWidth": 0.44,
    "realHeight": 0.5,
    "realDepth": 0.4,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "92f54a9d-4e8c-4149-91de-c182ec1f7b07",
    "type": "asset",
    "assetName": "piana",
    "categoryFolder": "counters-and-showcases",
    "label": "PIANA",
    "details": "Length/dept: 94 cm; Width: 144 cm; Height: 114 cm; Lockable: No; Illuminated: No; Frame: Wood; LED: No; Sustainable: No; Has plug: No",
    "x": 490,
    "y": 100,
    "rotation": 90,
    "width": 144,
    "height": 94,
    "specH": 1.14,
    "realWidth": 1.44,
    "realHeight": 1.14,
    "realDepth": 0.94,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "222ba5e4-5429-41d7-a0a0-f3a3768655a2",
    "type": "asset",
    "assetName": "pomp_square",
    "categoryFolder": "armchairs-sofas-and-lounges",
    "label": "POMP SQUARE",
    "details": "Length/dept: 100 cm; Width: 100 cm; Height: 50 cm; Sit height: 50 cm; Stackable: No; Swivel: No; Linkable: No; Frame: artificial leather; Sustainable: No; Seating: artificial leather",
    "x": 110.00000000000001,
    "y": 540,
    "rotation": 0,
    "width": 100,
    "height": 100,
    "specH": 0.5,
    "realWidth": 1,
    "realHeight": 0.5,
    "realDepth": 1,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  },
  {
    "id": "bc83f661-b7fb-49e3-b353-1f094baedf3d",
    "type": "asset",
    "assetName": "pomp_square",
    "categoryFolder": "armchairs-sofas-and-lounges",
    "label": "POMP SQUARE",
    "details": "Length/dept: 100 cm; Width: 100 cm; Height: 50 cm; Sit height: 50 cm; Stackable: No; Swivel: No; Linkable: No; Frame: artificial leather; Sustainable: No; Seating: artificial leather",
    "x": 270,
    "y": 540,
    "rotation": 0,
    "width": 100,
    "height": 100,
    "specH": 0.5,
    "realWidth": 1,
    "realHeight": 0.5,
    "realDepth": 1,
    "yOffset": 0,
    "verticalScale": 1,
    "facingOffset": 0
  }
];
